import os
import sys
import ast
import datetime
import importlib.util

# 常用库的导入名与pip安装名的映射表
# 很多库的import名字和pip install名字不一样，这里列出了一些最常见的
# 如果有其他特殊库，可以在这里手动添加
PACKAGE_MAPPINGS = {
    "cv2": "opencv-python",
    "PIL": "Pillow",
    "sklearn": "scikit-learn",
    "yaml": "PyYAML",
    "bs4": "beautifulsoup4",
    "usb": "pyusb",
    "serial": "pyserial",
    "telegram": "python-telegram-bot",
    "mysql": "mysql-connector-python",
    "docx": "python-docx",
    "dateutil": "python-dateutil",
    "lxml": "lxml",
    "dotenv": "python-dotenv",
    "jwt": "PyJWT",
    "paho": "paho-mqtt",
    "dns": "dnspython",
    "git": "GitPython",
    "zxingcpp": "pyrxing" # Mapped to pyrxing for Python 3.14 compatibility
}

def get_stdlib_names():
    """
    获取Python标准库名称集合，用于过滤不需要安装的包。
    """
    # Python 3.10+ 直接支持 sys.stdlib_module_names
    if sys.version_info >= (3, 10):
        return sys.stdlib_module_names
    
    # 旧版本回退策略：硬编码常用标准库列表
    return {
        "abc", "argparse", "ast", "asyncio", "base64", "collections", "contextlib",
        "copy", "csv", "datetime", "decimal", "email", "enum", "functools", "glob",
        "gzip", "hashlib", "html", "http", "importlib", "inspect", "io", "itertools",
        "json", "logging", "math", "multiprocessing", "os", "pathlib", "pickle",
        "platform", "pprint", "random", "re", "shutil", "signal", "socket", "sqlite3",
        "ssl", "statistics", "string", "subprocess", "sys", "tempfile", "threading",
        "time", "timeit", "tkinter", "traceback", "typing", "unittest", "urllib",
        "uuid", "warnings", "weakref", "xml", "zipfile", "zlib"
    }

def extract_imports_from_file(filepath):
    """
    使用 AST 解析单个 Python 文件中的导入项。
    """
    imports = set()
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            root = ast.parse(f.read(), filename=filepath)
        
        for node in ast.walk(root):
            # 处理 import xxx
            if isinstance(node, ast.Import):
                for alias in node.names:
                    imports.add(alias.name.split('.')[0])
            # 处理 from xxx import yyy
            elif isinstance(node, ast.ImportFrom):
                if node.module:
                    # 获取顶级模块名 (例如 from os.path import join -> os)
                    imports.add(node.module.split('.')[0])
    except Exception as e:
        print(f"警告: 无法解析文件 {filepath} - {e}")
    
    return imports

def main():
    root_dir = os.getcwd()
    all_imports = set()
    local_modules = set() # 记录本地文件名，防止把自己写的脚本误判为第三方库
    std_libs = get_stdlib_names()

    print(f"正在扫描目录: {root_dir} ...")

    # 1. 遍历文件，收集所有导入项和本地模块名
    py_files_count = 0
    for root, dirs, files in os.walk(root_dir):
        # 忽略常见的虚拟环境目录和隐藏目录
        dirs[:] = [d for d in dirs if d not in ['.git', '__pycache__', 'venv', 'env', '.idea', '.vscode']]
        
        for file in files:
            if file.endswith(".py") and file != "check-pip.py":
                full_path = os.path.join(root, file)
                module_name = file[:-3] # 去掉 .py
                local_modules.add(module_name)
                
                file_imports = extract_imports_from_file(full_path)
                all_imports.update(file_imports)
                py_files_count += 1

    print(f"已扫描 {py_files_count} 个 Python 文件。")

    # 2. 过滤
    third_party_packages = set()
    for name in all_imports:
        # 过滤标准库
        if name in std_libs:
            continue
        # 过滤本地模块 (同一目录下的其他脚本引用)
        if name in local_modules:
            continue
        # 过滤特殊名称 (如 private 模块)
        if name.startswith('_'):
            continue
            
        third_party_packages.add(name)

    # 3. 映射 import 名称到 pip 包名
    final_requirements = []
    for name in third_party_packages:
        # 如果在映射表中，使用映射后的名字，否则使用原名
        pkg_name = PACKAGE_MAPPINGS.get(name, name)
        final_requirements.append(pkg_name)

    final_requirements.sort()

    if not final_requirements:
        print("未检测到需要安装的第三方依赖。")
        return

    # 4. 生成输出文件
    timestamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
    output_filename = f"{timestamp}-pip.txt"
    
    # 构造命令字符串
    pip_command = f"pip install {' '.join(final_requirements)}"
    
    content = (
        f"# Generated by check-pip.py at {datetime.datetime.now()}\n"
        f"# Scanned {py_files_count} files.\n"
        f"# Found {len(final_requirements)} dependencies.\n\n"
        f"{pip_command}\n"
    )

    try:
        with open(output_filename, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"\n成功！依赖命令已写入: {output_filename}")
        print("-" * 30)
        print(pip_command)
        print("-" * 30)
    except Exception as e:
        print(f"写入文件失败: {e}")

if __name__ == "__main__":
    main()